### ISSUE TITLE
SHA256 on Core.Install 1.0.1 Fails

### ISSUE THREAD

**Issue by DustinVenegas** [jberezanski/dotnetcore-chocolateypackages#1]
Different SHA-256 hashes are causing the Chocolatey Package to fail. I am getting the following SHA hashes by hand:

- DotNetCore.1.0.1-Runtime-x86.exe: 8445CD876475F09EE7459701C759C9B9A73D452EAA6563E3F74132477F0DCC52
- DotNetCore.1.0.1-Runtime-x64.exe: CC6D028E60439698B8FA06D676CCB148F2147C747C50CBF7AF3353F3902D2411

**Comment by jberezanski** [comment]
Updated and pushed to chocolatey.org. Thanks for reporting this.
(Microsoft has updated the installers without changing the urls.)

**Comment by DustinVenegas** [comment]
Wow, that's a bit scary. Thanks for clarifying @jberezanski!
