### ISSUE TITLE
2.0.0 final package

### ISSUE THREAD

**Issue by mbp** [jberezanski/dotnetcore-chocolateypackages#10]
Would be great if the 2.0.0 final would be published to chocolatey :-)

**Comment by riezebosch** [comment]
Working on it.

**Comment by riezebosch** [comment]
@jberezanski I pushed all except for `aspnetcore-runtimepackagestore` because I'm no co-maintainer for that.

**Comment by mbp** [comment]
Since `aspnetcore-runtimepackagestore` is not published, it is currently not possible to install `dotnetcore-windowshosting` :-(

```
The install of dotnetcore-windowshosting was NOT successful.
dotnetcore-windowshosting not installed. An error occurred during installation:
 Unable to resolve dependency 'aspnetcore-runtimepackagestore (= 2.0.0)'.
```

**Comment by riezebosch** [comment]
Yes, I'm aware: https://chocolatey.org/packages/dotnetcore-windowshosting#comment-3478986687

**Comment by jberezanski** [comment]
@riezebosch I forgot to add you as maintainer when I added that package, sorry. I can see you've already resolved it with @gep13.

**Comment by riezebosch** [comment]
Yeah. Listed it again.
