### ISSUE TITLE
.NET Core 1.1.1 package

### ISSUE THREAD

**Issue by martincostello** [jberezanski/dotnetcore-chocolateypackages#7]
Now the SDK has RTM'd, the runtime has been updated again to 1.1.1.

**Comment by jberezanski** [comment]
Thanks for the heads-up! Would you like to submit a PR?

**Comment by martincostello** [comment]
I'll have a go if it's not something you're planning on working on anytime soon. I've never tried to do a Chocolatey package before.

**Comment by jberezanski** [comment]
Updating the packages to a newer minor version should be fairly painless and simple (much easier than creating new packages from scratch), so it might be a good start if you would like to learn about package authoring. If not, I'll probably be able to do it over the weekend.
